### ISSUE TITLE
Support LEFT(), RIGHT()

### ISSUE THREAD

**Issue by daverogers** [dominion-solutions/laravel-mysqlite#104]
I wasn't able to use `PDO::sqliteCreateFunction()` for LEFT/RIGHT because these are SQL keywords, so it would be great to use the `methodRewrite` functionality in this package to wrap these keywords in backticks and then implement the function extensions in `StringExtended`

Incoming MR 🙂

**Comment by daverogers** [comment]
@spam-n-eggs is this project abandoned? i can just maintain a separate fork if that's easier for you. i know open source projects are cool at first and then are a pain to maintain, esp if you're not using Laravel or PHP anymore 😆

**Comment by spam-n-eggs** [comment]
Hi Dave,



The project's not abandoned, I just haven't had a ton of time to maintain it.  I'm going to (eventually) move it to GitLab CI and run it in our FOSS group over there.  You just got me at a bad time - my parents just drove across the country over the past couple days, and as luck would have it, the power supply for my Dominion Solutions laptop died at the same time.  I'll take a look at your PR this morning.







Mark Joseph Horninger,

Principal Engineer, Dominion Solutions LLC

+1 484-475-8550

***@***.***

https://dominion.solutions








---- On Wed, 12 Apr 2023 16:51:31 -0400 Dave Rogers ***@***.***> wrote ---





https://github.com/spam-n-eggs is this project abandoned? i can just maintain a separate fork if that's easier for you. i know open source projects are cool at first and then are a pain to maintain, esp if you're not using Laravel or PHP anymore 😆
